[package]
name = "discovery-explore"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-broadcast = "0.4"
once_cell = "1"
parking_lot = "0.12"
http = "*"